bundler_args: ''
language: ruby
gemfile:
  - Gemfile
  - spec/gemfiles/40.gemfile
  - spec/gemfiles/41.gemfile
  - spec/gemfiles/42.gemfile
matrix:
  exclude:
script: bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: never
